/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author Administrador
 */
public class NewUpdateCliente extends javax.swing.JDialog {

    /**
     * Creates new form NewUpdateCliente
     */
    public NewUpdateCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlClienteDetails = new javax.swing.JPanel();
        lblClienteNickname = new javax.swing.JLabel();
        txtClienteNickname = new javax.swing.JTextField();
        lblClienteId = new javax.swing.JLabel();
        txtClienteId = new javax.swing.JTextField();
        lblClienteNombre = new javax.swing.JLabel();
        txtClienteNombre = new javax.swing.JTextField();
        lblClienteAltura = new javax.swing.JLabel();
        txtClienteAltura = new javax.swing.JTextField();
        lblClientePeso = new javax.swing.JLabel();
        txtClientePeso = new javax.swing.JTextField();
        pnlClienteFoto = new javax.swing.JPanel();
        lblClienteFoto = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlClienteDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                pnlClienteDetailsComponentHidden(evt);
            }
        });
        pnlClienteDetails.setLayout(new java.awt.GridBagLayout());

        lblClienteNickname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClienteNickname.setText("Nickname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(lblClienteNickname, gridBagConstraints);

        txtClienteNickname.setEditable(false);
        txtClienteNickname.setBackground(new java.awt.Color(255, 255, 255));
        txtClienteNickname.setText("Nickname");
        txtClienteNickname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 203;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(txtClienteNickname, gridBagConstraints);

        lblClienteId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClienteId.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(lblClienteId, gridBagConstraints);

        txtClienteId.setEditable(false);
        txtClienteId.setBackground(new java.awt.Color(255, 255, 255));
        txtClienteId.setText("ID");
        txtClienteId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(txtClienteId, gridBagConstraints);

        lblClienteNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClienteNombre.setText("Nombre y apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(lblClienteNombre, gridBagConstraints);

        txtClienteNombre.setEditable(false);
        txtClienteNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtClienteNombre.setText("Nombre y apellidos");
        txtClienteNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 231;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(txtClienteNombre, gridBagConstraints);

        lblClienteAltura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClienteAltura.setText("Altura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(lblClienteAltura, gridBagConstraints);

        txtClienteAltura.setEditable(false);
        txtClienteAltura.setBackground(new java.awt.Color(255, 255, 255));
        txtClienteAltura.setText("Altura");
        txtClienteAltura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(txtClienteAltura, gridBagConstraints);

        lblClientePeso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClientePeso.setText("Peso");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(lblClientePeso, gridBagConstraints);

        txtClientePeso.setEditable(false);
        txtClientePeso.setBackground(new java.awt.Color(255, 255, 255));
        txtClientePeso.setText("Peso");
        txtClientePeso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(txtClientePeso, gridBagConstraints);

        pnlClienteFoto.setLayout(new java.awt.BorderLayout());

        lblClienteFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClienteFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/profile.png"))); // NOI18N
        lblClienteFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlClienteFoto.add(lblClienteFoto, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(pnlClienteFoto, gridBagConstraints);

        btnCancel.setText("Cancelar");
        btnCancel.setMaximumSize(new java.awt.Dimension(100, 25));
        btnCancel.setMinimumSize(new java.awt.Dimension(100, 25));
        btnCancel.setPreferredSize(new java.awt.Dimension(100, 25));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(btnCancel, gridBagConstraints);

        btnSave.setText("Guardar");
        btnSave.setMaximumSize(new java.awt.Dimension(100, 25));
        btnSave.setMinimumSize(new java.awt.Dimension(100, 25));
        btnSave.setPreferredSize(new java.awt.Dimension(100, 25));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(btnSave, gridBagConstraints);

        getContentPane().add(pnlClienteDetails, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 703, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    }//GEN-LAST:event_btnSaveActionPerformed

    private void pnlClienteDetailsComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlClienteDetailsComponentHidden
    }//GEN-LAST:event_pnlClienteDetailsComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUpdateCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUpdateCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUpdateCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUpdateCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewUpdateCliente dialog = new NewUpdateCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblClienteAltura;
    private javax.swing.JLabel lblClienteFoto;
    private javax.swing.JLabel lblClienteId;
    private javax.swing.JLabel lblClienteNickname;
    private javax.swing.JLabel lblClienteNombre;
    private javax.swing.JLabel lblClientePeso;
    private javax.swing.JPanel pnlClienteDetails;
    private javax.swing.JPanel pnlClienteFoto;
    private javax.swing.JTextField txtClienteAltura;
    private javax.swing.JTextField txtClienteId;
    private javax.swing.JTextField txtClienteNickname;
    private javax.swing.JTextField txtClienteNombre;
    private javax.swing.JTextField txtClientePeso;
    // End of variables declaration//GEN-END:variables
}
