/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.data.ClienteController;
import controller.data.EjercicioController;
import controller.exception.EntityControllersException;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        cardLayout = (CardLayout) pnlDataDetails.getLayout();
        listModel = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTableButtons = new javax.swing.JPanel();
        pnlTablesFillLeft = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnTableClientes = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 35), new java.awt.Dimension(0, 35), new java.awt.Dimension(32767, 35));
        btnTableEjercicios = new javax.swing.JButton();
        pnlTablesFillRight = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        pnlData = new javax.swing.JSplitPane();
        pnlDataList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstData = new javax.swing.JList<>();
        pnlDataDetails = new javax.swing.JPanel();
        pnlSearchLogo = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        lblSearchIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        pnlClienteDetails = new javax.swing.JPanel();
        lblClienteNickname = new javax.swing.JLabel();
        txtClienteNickname = new javax.swing.JTextField();
        lblClienteId = new javax.swing.JLabel();
        txtClienteId = new javax.swing.JTextField();
        lblClienteNombre = new javax.swing.JLabel();
        txtClienteNombre = new javax.swing.JTextField();
        lblClienteAltura = new javax.swing.JLabel();
        txtClienteAltura = new javax.swing.JTextField();
        lblClientePeso = new javax.swing.JLabel();
        txtClientePeso = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstClienteRelacion = new javax.swing.JList<>();
        pnlClienteFoto = new javax.swing.JPanel();
        lblClienteFoto = new javax.swing.JLabel();
        pnlEjercicioDetails = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        menuItemConfig = new javax.swing.JMenu();
        menuItemHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 460));
        setPreferredSize(new java.awt.Dimension(920, 460));

        pnlTableButtons.setLayout(new javax.swing.BoxLayout(pnlTableButtons, javax.swing.BoxLayout.LINE_AXIS));
        pnlTableButtons.add(pnlTablesFillLeft);

        btnTableClientes.setText("Clientes");
        btnTableClientes.setMaximumSize(new java.awt.Dimension(100, 25));
        btnTableClientes.setMinimumSize(new java.awt.Dimension(100, 25));
        btnTableClientes.setPreferredSize(new java.awt.Dimension(100, 25));
        btnTableClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableClientesActionPerformed(evt);
            }
        });
        pnlTableButtons.add(btnTableClientes);
        pnlTableButtons.add(filler1);

        btnTableEjercicios.setText("Ejercicios");
        btnTableEjercicios.setMaximumSize(new java.awt.Dimension(100, 25));
        btnTableEjercicios.setMinimumSize(new java.awt.Dimension(100, 25));
        btnTableEjercicios.setPreferredSize(new java.awt.Dimension(100, 25));
        btnTableEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableEjerciciosActionPerformed(evt);
            }
        });
        pnlTableButtons.add(btnTableEjercicios);
        pnlTableButtons.add(pnlTablesFillRight);

        getContentPane().add(pnlTableButtons, java.awt.BorderLayout.NORTH);

        pnlData.setDividerLocation(120);

        pnlDataList.setMinimumSize(new java.awt.Dimension(100, 100));
        pnlDataList.setLayout(new javax.swing.BoxLayout(pnlDataList, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(50, 50));

        lstData.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstData);

        pnlDataList.add(jScrollPane1);

        pnlData.setLeftComponent(pnlDataList);

        pnlDataDetails.setLayout(new java.awt.CardLayout());

        pnlSearchLogo.setLayout(new java.awt.GridLayout(0, 1));
        pnlSearchLogo.add(filler2);

        lblSearchIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/search_icon.png"))); // NOI18N
        pnlSearchLogo.add(lblSearchIcon);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pulsa sobre la lista para visualizar detalles.");
        pnlSearchLogo.add(jLabel1);
        pnlSearchLogo.add(filler3);

        pnlDataDetails.add(pnlSearchLogo, "logo");
        pnlSearchLogo.getAccessibleContext().setAccessibleName("pnlSearchLogo");

        pnlClienteDetails.setLayout(new java.awt.GridBagLayout());

        lblClienteNickname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClienteNickname.setText("Nickname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(lblClienteNickname, gridBagConstraints);

        txtClienteNickname.setEditable(false);
        txtClienteNickname.setBackground(new java.awt.Color(255, 255, 255));
        txtClienteNickname.setText("Nickname");
        txtClienteNickname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 203;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(txtClienteNickname, gridBagConstraints);

        lblClienteId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClienteId.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(lblClienteId, gridBagConstraints);

        txtClienteId.setEditable(false);
        txtClienteId.setBackground(new java.awt.Color(255, 255, 255));
        txtClienteId.setText("ID");
        txtClienteId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(txtClienteId, gridBagConstraints);

        lblClienteNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClienteNombre.setText("Nombre y apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(lblClienteNombre, gridBagConstraints);

        txtClienteNombre.setEditable(false);
        txtClienteNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtClienteNombre.setText("Nombre y apellidos");
        txtClienteNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 231;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(txtClienteNombre, gridBagConstraints);

        lblClienteAltura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClienteAltura.setText("Altura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(lblClienteAltura, gridBagConstraints);

        txtClienteAltura.setEditable(false);
        txtClienteAltura.setBackground(new java.awt.Color(255, 255, 255));
        txtClienteAltura.setText("Altura");
        txtClienteAltura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(txtClienteAltura, gridBagConstraints);

        lblClientePeso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClientePeso.setText("Peso");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(lblClientePeso, gridBagConstraints);

        txtClientePeso.setEditable(false);
        txtClientePeso.setBackground(new java.awt.Color(255, 255, 255));
        txtClientePeso.setText("Peso");
        txtClientePeso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(txtClientePeso, gridBagConstraints);

        lstClienteRelacion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstClienteRelacion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 484;
        gridBagConstraints.ipady = 147;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(jScrollPane3, gridBagConstraints);

        pnlClienteFoto.setMinimumSize(new java.awt.Dimension(128, 128));
        pnlClienteFoto.setPreferredSize(new java.awt.Dimension(128, 128));
        pnlClienteFoto.setLayout(new java.awt.BorderLayout());

        lblClienteFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClienteFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/profile.png"))); // NOI18N
        lblClienteFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlClienteFoto.add(lblClienteFoto, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        pnlClienteDetails.add(pnlClienteFoto, gridBagConstraints);

        pnlDataDetails.add(pnlClienteDetails, "cliente");

        javax.swing.GroupLayout pnlEjercicioDetailsLayout = new javax.swing.GroupLayout(pnlEjercicioDetails);
        pnlEjercicioDetails.setLayout(pnlEjercicioDetailsLayout);
        pnlEjercicioDetailsLayout.setHorizontalGroup(
            pnlEjercicioDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        pnlEjercicioDetailsLayout.setVerticalGroup(
            pnlEjercicioDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        pnlDataDetails.add(pnlEjercicioDetails, "ejercicio");

        pnlData.setRightComponent(pnlDataDetails);

        getContentPane().add(pnlData, java.awt.BorderLayout.CENTER);

        menuItemConfig.setText("Ajustes");
        menu.add(menuItemConfig);

        menuItemHelp.setText("Ayuda");
        menu.add(menuItemHelp);

        setJMenuBar(menu);

        setSize(new java.awt.Dimension(814, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTableClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableClientesActionPerformed

        new Thread(
                loadJListTask("cliente")
        ).start();

    }//GEN-LAST:event_btnTableClientesActionPerformed


    private void btnTableEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableEjerciciosActionPerformed

        new Thread(
                loadJListTask("ejercicio")
        ).start();

    }//GEN-LAST:event_btnTableEjerciciosActionPerformed
    //TODO: Remove MAIN CALL.
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    DefaultListModel<Object> listModel;
    CardLayout cardLayout;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTableClientes;
    private javax.swing.JButton btnTableEjercicios;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblClienteAltura;
    private javax.swing.JLabel lblClienteFoto;
    private javax.swing.JLabel lblClienteId;
    private javax.swing.JLabel lblClienteNickname;
    private javax.swing.JLabel lblClienteNombre;
    private javax.swing.JLabel lblClientePeso;
    private javax.swing.JLabel lblSearchIcon;
    private javax.swing.JList<String> lstClienteRelacion;
    private javax.swing.JList<Object> lstData;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuItemConfig;
    private javax.swing.JMenu menuItemHelp;
    private javax.swing.JPanel pnlClienteDetails;
    private javax.swing.JPanel pnlClienteFoto;
    private javax.swing.JSplitPane pnlData;
    private javax.swing.JPanel pnlDataDetails;
    private javax.swing.JPanel pnlDataList;
    private javax.swing.JPanel pnlEjercicioDetails;
    private javax.swing.JPanel pnlSearchLogo;
    private javax.swing.JPanel pnlTableButtons;
    private javax.swing.Box.Filler pnlTablesFillLeft;
    private javax.swing.Box.Filler pnlTablesFillRight;
    private javax.swing.JTextField txtClienteAltura;
    private javax.swing.JTextField txtClienteId;
    private javax.swing.JTextField txtClienteNickname;
    private javax.swing.JTextField txtClienteNombre;
    private javax.swing.JTextField txtClientePeso;
    // End of variables declaration//GEN-END:variables

    public Runnable loadJListTask(String cardTarget) {
        boolean isClienteTable = cardTarget.equals("cliente");
        return (Runnable) () -> {
            try {
                listModel.removeAllElements();
                listModel.addAll(
                        isClienteTable
                                ? ClienteController.getInstance().getListadoClientes()
                                : EjercicioController.getInstance().getAllEjercicios()
                );
                lstData.setModel(listModel);
                btnTableClientes.setEnabled(!isClienteTable);
                btnTableEjercicios.setEnabled(isClienteTable);
                
            } catch (EntityControllersException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
            cardLayout.show(pnlDataDetails, "cliente");
        };
    }

}
